[book]
authors = ["Kasi Chennupati"]
language = "en"
multilingual = false
src = "src"
title = "Data Projects Index"
text-direction = "ltr"

[build]
build-dir = "docs"
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding




