[book]
authors = ["Kasi Chennupati"]
language = "en"
multilingual = false
src = "src"
title = "Data Projects Index"
text-direction = "ltr"

[build]
build-dir = "docs"
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false



